# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rtsne_cpp <- function(X_in, no_dims_in, perplexity_in, theta_in, verbose, max_iter, distance_precomputed) {
    .Call('Rtsne_Rtsne_cpp', PACKAGE = 'Rtsne', X_in, no_dims_in, perplexity_in, theta_in, verbose, max_iter, distance_precomputed)
}

